version: '3.8'

services:
  build-gos:
    image: ghcr.io/lucasbeiler/build_grapheneos:latest
    env_file: "/etc/reproducible-builds-grapheneos.env"
    volumes:
      - ~/comparing/:/opt/build/grapheneos/comparing/
      - /etc/gitcookies:/.gitcookies
    privileged: true
    stdin_open: true
    tty: true
    user: reprobuilder
    restart: "no"

  compare-gos:
    image: ghcr.io/lucasbeiler/compare_grapheneos_builds:latest
    env_file: "/etc/reproducible-builds-grapheneos.env"
    volumes:
      - ~/comparing/:/opt/build/grapheneos/comparing/
    stdin_open: true
    tty: true
    user: comparer
    restart: "no"